"""
chatbot.py
-----------
A fully offline, rule-based conversational "guided check-in" flow.

The conversation flow itself is a deterministic state machine, not an LLM:
anyone can clone the repo and complete a full check-in with zero API keys
and zero network dependency. The "AI" doing the actual work is the trained
risk/persona models; this module just walks the user through the same
inputs those models expect and parses free-text answers.

The one optional exception is the final explanation text, which can be
generated by an LLM via llm_explainer.explain() if GROQ_API_KEY or GEMINI_API_KEY is
set (see main.py) - purely to phrase the already-computed numbers more
naturally. It never changes the score, tier, persona, or escalation
decision, and silently falls back to a template without a key.

A lightweight safety net scans every message for crisis language and
will surface crisis resources immediately, regardless of what stage of
the check-in the user is in.
"""

import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional

from recommender import CheckInInput, build_recommendation, CRISIS_RESOURCES

STEPS = [
    "age",
    "screen_time_hrs",
    "sleep_quality",
    "stress_level",
    "days_without_social_media",
    "exercise_frequency",
    "happiness_index",
]

PROMPTS = {
    "age": "First, how old are you?",
    "screen_time_hrs": "Roughly how many hours a day are you on your phone/screens right now?",
    "sleep_quality": "On a scale of 1-10, how would you rate your sleep quality lately?",
    "stress_level": "On a scale of 1-10, how stressed have you been feeling?",
    "days_without_social_media": "How many days has it been since your last social media break?",
    "exercise_frequency": "How many times did you exercise this past week?",
    "happiness_index": "Last one - on a scale of 1-10, how happy would you say you feel overall right now?",
}

RANGE_HINTS = {
    "sleep_quality": (1, 10),
    "stress_level": (1, 10),
    "happiness_index": (1, 10),
}

CRISIS_KEYWORDS = [
    "kill myself", "suicide", "want to die", "end my life", "can't go on",
    "self harm", "self-harm", "hurt myself", "no reason to live",
]

_NUMBER_RE = re.compile(r"-?\d+(\.\d+)?")


@dataclass
class ChatSession:
    step_index: int = 0
    answers: Dict[str, float] = field(default_factory=dict)
    done: bool = False


SESSIONS: Dict[str, ChatSession] = {}


def _get_session(session_id: str) -> ChatSession:
    if session_id not in SESSIONS:
        SESSIONS[session_id] = ChatSession()
    return SESSIONS[session_id]


def _extract_number(text: str) -> Optional[float]:
    match = _NUMBER_RE.search(text.replace(",", "."))
    if not match:
        return None
    return float(match.group(0))


def _contains_crisis_language(text: str) -> bool:
    lowered = text.lower()
    return any(k in lowered for k in CRISIS_KEYWORDS)


def crisis_response() -> dict:
    return {
        "message": (
            "Thank you for telling me. I can't provide crisis counselling, but you deserve "
            "support right now, and reaching out to a real person is the best next step. "
            "Please consider contacting one of these right away:"
        ),
        "crisis_resources": CRISIS_RESOURCES,
        "done": False,
        "escalated": True,
    }


def start_session(session_id: str) -> dict:
    SESSIONS[session_id] = ChatSession()
    return {
        "message": (
            "Hi, I'm the PulseCheck guided check-in. I'll ask a handful of quick questions "
            "about how you've been doing, then give you a personalised read on your current "
            "wellness load plus a couple of things you can do right now. "
            + PROMPTS[STEPS[0]]
        ),
        "done": False,
        "escalated": False,
    }


def handle_message(session_id: str, text: str, predictor, explainer=None) -> dict:
    """
    predictor: callable(CheckInInput) -> (risk_score: float, persona: str)
    explainer: optional callable(**kwargs) -> {"text": str, "source": str}
               (see llm_explainer.explain). If omitted, no ai_explanation
               field is added.
    """
    if _contains_crisis_language(text):
        return crisis_response()

    session = _get_session(session_id)

    if session.done:
        return start_session(session_id)

    current_key = STEPS[session.step_index]
    value = _extract_number(text)

    if value is None:
        return {
            "message": f"I didn't catch a number there. {PROMPTS[current_key]}",
            "done": False,
            "escalated": False,
        }

    if current_key in RANGE_HINTS:
        lo, hi = RANGE_HINTS[current_key]
        value = max(lo, min(hi, value))

    session.answers[current_key] = value
    session.step_index += 1

    if session.step_index < len(STEPS):
        next_key = STEPS[session.step_index]
        return {
            "message": PROMPTS[next_key],
            "done": False,
            "escalated": False,
        }

    # All answers collected -> run the model pipeline
    session.done = True
    check_in = CheckInInput(
        age=session.answers["age"],
        screen_time_hrs=session.answers["screen_time_hrs"],
        sleep_quality=session.answers["sleep_quality"],
        stress_level=session.answers["stress_level"],
        days_without_social_media=session.answers["days_without_social_media"],
        exercise_frequency=session.answers["exercise_frequency"],
        happiness_index=session.answers["happiness_index"],
    )
    risk_score, persona = predictor(check_in)
    rec = build_recommendation(check_in, risk_score, persona)

    ai_explanation = None
    if explainer is not None:
        ai_explanation = explainer(
            risk_score=rec.risk_score,
            risk_tier=rec.risk_tier,
            persona=rec.persona,
            stress_level=check_in.stress_level,
            sleep_quality=check_in.sleep_quality,
            screen_time_hrs=check_in.screen_time_hrs,
            happiness_index=check_in.happiness_index,
            exercise_frequency=check_in.exercise_frequency,
            days_without_social_media=check_in.days_without_social_media,
        )

    tips_text = "\n".join(f"- {t}" for t in rec.tips)
    message = (
        f"{rec.headline}\n\n"
        f"Risk score: {rec.risk_score}/10 ({rec.risk_tier})\n"
        f"Wellness persona: {rec.persona}\n\n"
        f"A few things to try right now:\n{tips_text}"
    )
    if ai_explanation:
        message += f"\n\n{ai_explanation['text']}"

    return {
        "message": message,
        "done": True,
        "escalated": rec.escalate,
        "risk_score": rec.risk_score,
        "risk_tier": rec.risk_tier,
        "persona": rec.persona,
        "tips": rec.tips,
        "crisis_resources": rec.crisis_resources,
        "ai_explanation": ai_explanation,
    }
